### ISSUE TITLE
libvas.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by randomsymbols** [OneIdentity/mod_auth_vas#4]
[FAIL] Restarting Apache httpd web server: apache2 failed!
[warn] The apache2 configtest failed. ... (warning).
Output of config test was:
apache2: Syntax error on line 146 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/auth_vas4.load: Cannot load /usr/lib/apache2/modules/mod_auth_vas4.so into server: libvas.so.4: cannot open shared object file: No such file or directory
Action 'configtest' failed.
The Apache error log may have more information.

OS: Debian Linux 9
Apache 2.4.25
mod-auth-vas-ap24_4.0.2.4-1_amd64.deb

**Comment by TylerReese** [comment]
@JaysonHurst can you look at this?

**Comment by JaysonHurst** [comment]
Can you provide more information about this failure? The logs that were produced, what version of QAS you are running?  What is the output from running:

$ ldd /usr/lib/apache2/modules/mod_auth_vas4.so

Does libvas.so.4 exist on the box, it should be found in ether /opt/quest/lib64/ or /opt/quest/lib

**Comment by manner82** [comment]
Works for me on debian9.
The error means that apache fails to load the library. That can be of various reasons, you might get a clue with running:
ldd /usr/lib/apache2/modules/mod_auth_vas4.so

As an example, here is what I have done to debug my problem:
```
# I start a debian 9:
$ docker run -it debian:9 /bin/bash
Unable to find image 'debian:9' locally
9: Pulling from library/debian
2587235a7635: Pull complete 
Digest: sha256:7f2706b124ee835c3bcd7dc81d151d4f5eca3f4306c5af5c73848f5f89f10e0b
Status: Downloaded newer image for debian:9

# I install apache2:
$ apt update && apt -y install apache2
...

# Let's install mod_auth_vas:
$ dpkg -i mod-auth-vas-ap24_4.0.2.4-1_amd64.deb
...
$ service apache2 restart
[FAIL] Restarting Apache httpd web server: apache2 failed!
apache2: Syntax error on line 146 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/auth_vas4.load: Cannot load /usr/lib/apache2/modules/mod_auth_vas4.so into server: libvas.so.4: cannot open shared object file: No such file or directory
Action 'configtest' failed.

# Notice, this has failed... What the hack is going on??
$ ldd /usr/lib/apache2/modules/mod_auth_vas4.so
	linux-vdso.so.1 (0x00007ffd772d4000)
	libvas.so.4 => not found
	libapr-1.so.0 => /usr/lib/x86_64-linux-gnu/libapr-1.so.0 (0x00007fe0a4f9e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe0a4d81000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe0a49e2000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fe0a47dd000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe0a45d5000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fe0a439d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe0a4199000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe0a53e7000)

# Notice it does not find the libvas.so.4 library. Let's install it:
$ dpkg -i vasclnt_5.0.0-25769_amd64.deb

# I verify I have fixed it:
$ ldd /usr/lib/apache2/modules/mod_auth_vas4.so
...
     libvas.so.4 => /opt/quest/lib64/libvas.so.4 (0x00007f056207a000)
...

$ service apache2 restart
Restarting Apache httpd web server: OK
```

**Comment by manner82** [comment]
I propose we close this.
